Repository srm-kzilla/jack, pull requests merged in 2021-02, with the labels that each got.

#18 📝 Update README.md
  README.md
Labels: documentation

#19 Refactor: Architecture Change
  README.md
  index.ts
  src/controllers/incomingMessageHandler.ts
  src/controllers/sendMessageHandler.ts
  src/helper/announcement.ts
  src/helper/certificate.ts
  src/helper/flushCache.ts
  src/helper/jokes.ts
  src/helper/kzillaXYZ.ts
  src/helper/memberCount.ts
  src/helper/memberLogs.ts
  src/helper/polls.ts
  src/models/incomingMessage.ts
  src/models/poll.ts
  src/service/certificate-service.ts
  src/utils/constants.ts
  src/utils/messages.ts
Labels: bug, enhancement

#20 Add Webhook Role Manager
  .env.sample
  .gitignore
  Procfile
  ecosystem.config.js
  index.ts
  package.json
  src/api/app.ts
  src/api/error/error.constant.ts
  src/api/error/error.handler.ts
  src/api/middlewares/validate-query.ts
  src/api/middlewares/validate-webhook.ts
  src/api/roles/roles.routes.ts
  src/api/roles/roles.schema.ts
  src/api/roles/roles.service.ts
  yarn.lock
Labels: enhancement
